### ISSUE TITLE
Сборка БЭМ-проекта, c подключением НЕ использующегося css.

### ISSUE THREAD

**Issue by woltoe** [dab/html2bl#2]
Собственно, как сделать так, чтобы при сборке проекта (для styles.css):
1. Сохранялся порядок подключаемых css-файлов.
2. Для неиспользующихся сущностей на данной странице, css тем не менее подключался в общий файл.
3. Непосредственно в самый конец, для каждого уровня переопределения.

На вопрос натолкнули размышления после просмотра вэбинара по сборке и оптимизации БЭМ проекта с помощью gulp.

**Comment by dab** [comment]
Привет, прошу прощения за поздний ответ. 
- Порядок подключаемых блоков определяется их порядком в исходном html файле.
- Для этого стоит добавить неиспользуемые css на уровне сборки. Результатом выполнения `html2bl` является массив с путями, можно сравнивать его со списком всех доступных блоков и добавлять оставшиеся в нужном месте в нужное время.

С оптимизмом.
